name: env_win
channels:
  - defaults
dependencies:
  - certifi=2018.8.24=py37_1
  - pip=10.0.1=py37_0
  - python=3.7.0=hea74fb7_0
  - setuptools=40.2.0=py37_0
  - vc=14=h0510ff6_3
  - vs2015_runtime=14.0.25123=3
  - wheel=0.31.1=py37_0
  - wincertstore=0.2=py37_0
